### ISSUE TITLE
Inserir Bagdes pra o ranking e o hall da fama 

### ISSUE THREAD

**Issue by marimendes** [TeamBasedLearning/PGTBL#8]
Os pontos variam de 0 a 3000.

## Positivas:
Bagde 1: Grupo conseguir 500 pontos.
Badge 2: Grupo conseguir 1500 pontos.
Badge 3: Grupo conseguir 3000 pontos.
Badge 4: Ficar em primeiro lugar em pelo menos uma sessão de TBL
Badge 5: Ficar em primeiro lugar em todas as sessões.
Bagde 6: O grupo com a média de pontos iguais e a média precisa ser acima de 500 pontos.

## Negativas:
Badge 1: O grupo com a média de pontos abaixo de 500 pontos.

**Comment by marimendes** [comment]
https://www.flaticon.com/search?word=badge

**Comment by VictorDeon** [comment]
Ficar em primeiro lugar em pelo menos uma sessão de TBL

![medalha](https://user-images.githubusercontent.com/14116020/48033003-c4c1ec80-e140-11e8-8e1b-bef10f50f3c4.png)

**Comment by VictorDeon** [comment]
Ficar em primeiro lugar em todas as sessões.

![trophy](https://user-images.githubusercontent.com/14116020/48033174-69442e80-e141-11e8-8fe7-fa008ffde953.png)

**Comment by VictorDeon** [comment]
Bagde 1: Grupo conseguir 500 pontos.

http://www.iconarchive.com/show/role-playing-icons-by-chanut/Villager-icon.html

Badge 2: Grupo conseguir 1500 pontos.

http://www.iconarchive.com/show/role-playing-icons-by-chanut/Viking-icon.html

Badge 3: Grupo conseguir 3000 pontos.

http://www.iconarchive.com/show/role-playing-icons-by-chanut/King-icon.html

**Comment by VictorDeon** [comment]
O grupo com a média de pontos iguais e a média precisa ser acima de 500 pontos.

http://www.iconarchive.com/show/role-playing-icons-by-chanut.html
